language: python
python:
  - "2.6"
  - "2.7"
install:
  pip install -r requirements.txt
before_script:
  pip install nose coverage coveralls
script:
  nosetests
after_success:
  echo -e "[report]\nomit =\n    tests/*" > .coverage.rc
  coveralls
